name: Build and release

permissions:
  contents: write

on:
  push:
    tags:
      - '*'

jobs:
  build_and_release:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Setup build prerequisites
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq -y --no-install-recommends make libgtk-3-dev

      - name: Build binaries
        run: |
          make all

      - name: Create GitHub release
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            rg-downloader
            rg-downloader.exe
